<!--
  ~     Copyright 2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  ~
  ~     Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with the License.
  ~     A copy of the License is located at
  ~
  ~         http://aws.amazon.com/apache2.0/
  ~
  ~     or in the "license" file accompanying this file.
  ~     This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~     See the License for the specific language governing permissions and limitations under the License.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.jenkins-ci.plugins</groupId>
        <artifactId>plugin</artifactId>
        <version>6.2221.va_045130417c9</version>
        <relativePath/>
    </parent>

    <groupId>com.amazonaws</groupId>
    <artifactId>aws-codebuild</artifactId>
    <version>0.60-SNAPSHOT</version>
    <packaging>hpi</packaging>
    <name>AWS CodeBuild Plugin</name>
    <description>Adds a build step to integrate Jenkins with AWS CodeBuild.</description>
    <url>https://wiki.jenkins.io/display/JENKINS/AWS+CodeBuild+Plugin</url>

    <properties>
        <jenkins.version>2.541.3</jenkins.version>
    </properties>

    <developers>
        <developer>
            <id>leobaran</id>
            <name>Leo Baran</name>
            <email>leobaran@amazon.com</email>
        </developer>
        <developer>
            <id>subinataws</id>
            <name>CodeBuild</name>
            <email>subinm@amazon.com</email>
        </developer>
    </developers>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <url>https://github.com/jenkinsci/aws-codebuild-plugin</url>
        <connection>scm:git:ssh://github.com/jenkinsci/aws-codebuild-plugin.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/jenkinsci/aws-codebuild-plugin.git</developerConnection>
        <tag>HEAD</tag>
    </scm>

    <!-- get every artifact through repo.jenkins-ci.org, which proxies all the
        artifacts that we need -->
    <repositories>
        <repository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/public/</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/public/</url>
        </pluginRepository>
    </pluginRepositories>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.jenkins-ci.tools</groupId>
                    <artifactId>maven-hpi-plugin</artifactId>
                    <configuration>
                        <disabledTestInjection>true</disabledTestInjection>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>0.8.4</version>
                    <executions>
                        <execution>
                            <id>pre-unit-test</id>
                            <goals>
                                <goal>prepare-agent</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>post-unit-test</id>
                            <phase>test</phase>
                            <goals>
                                <goal>report</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <!-- TODO: merge with Parent POM? -->
                <groupId>com.github.spotbugs</groupId>
                <artifactId>spotbugs-maven-plugin</artifactId>
                <configuration>
                    <excludeFilterFile>findbugs-exclude.xml</excludeFilterFile>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.4</version>
            </plugin>
        </plugins>
    </build>

    <distributionManagement>
        <repository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/releases</url>
        </repository>
    </distributionManagement>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.jenkins.tools.bom</groupId>
                <artifactId>bom-2.541.x</artifactId>
                <version>6931.vea_a_b_c6fd017d</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- sdk2's apache-client wants httpclient 4.5.13; force the Jenkins plugin's 4.5.14 for RequireUpperBoundDeps -->
            <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpclient</artifactId>
                <version>4.5.14</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.jenkins.plugins.aws-java-sdk2</groupId>
            <artifactId>aws-java-sdk2-codebuild</artifactId>
            <version>2.42.33-70.vd69c0763fa_60</version>
        </dependency>
        <dependency>
            <groupId>io.jenkins.plugins.aws-java-sdk2</groupId>
            <artifactId>aws-java-sdk2-s3</artifactId>
            <version>2.42.33-70.vd69c0763fa_60</version>
        </dependency>
        <dependency>
            <groupId>io.jenkins.plugins.aws-java-sdk2</groupId>
            <artifactId>aws-java-sdk2-cloudwatchlogs</artifactId>
            <version>2.42.33-70.vd69c0763fa_60</version>
        </dependency>
        <!-- raw SDK module (no current sdk2-sts plugin); version must match the aws-java-sdk2-* plugins' SDK -->
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>sts</artifactId>
            <version>2.42.33</version>
        </dependency>
        <dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>credentials</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>cloudbees-folder</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jenkins-ci.plugins.workflow</groupId>
            <artifactId>workflow-step-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>script-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>jackson2-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>5.23.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.objenesis</groupId>
            <artifactId>objenesis</artifactId>
            <version>3.0.1</version>
        </dependency>
        <dependency>
            <groupId>net.lingala.zip4j</groupId>
            <artifactId>zip4j</artifactId>
            <version>2.11.6</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.42</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
